version: "3.6"
services: 

    mvp:
        build: .
        container_name: 'mvp'
        restart: always
        ports:
            - "5001:5001"
    mvp_krakend:
        image: devopsfaith/krakend:1.4.0
        container_name: 'mvp_krakend'
        restart: always
        volumes:
            -   ./krakend:/etc/krakend/
        depends_on:
            - mvp
        environment:
            - "KRAKEND_HOST=192.168.1.197:5001"
        ports:
            -   "8080:8080"