version: "3.6"
services:
    mvp_db:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT: root
            MYSQL_ROOT_PASSWORD: pass@123
        ports:
            - "3306:3306"

    mvp:
        build: .
        container_name: 'mvp'
        restart: always
        depends_on:
            - mvp_db
        ports:
            - "5001:5001"
    mvp_krakend:
        image: devopsfaith/krakend:1.4.0
        container_name: 'mvp_krakend'
        restart: always
        volumes:
            -   ./krakend:/etc/krakend/
        depends_on:
            - mvp
            - mvp_db
        environment:
            - "KRAKEND_HOST=192.168.1.197:5001"
        ports:
            -   "8080:8080"